name: Android Debug APK (Tags)

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build-android-debug:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Accept Android licenses
        shell: bash
        run: yes | "${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager" --licenses

      - name: Install required SDK components (NDK 29)
        shell: bash
        run: yes | "${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager" "ndk;29.0.13113456"

      - name: Flutter pub get
        run: flutter pub get

      - name: Build debug APK (Render URL)
        run: |
          flutter build apk --debug \
            --android-skip-build-dependency-validation \
            --dart-define=API_BASE_URL=https://movie-app-backend-o85w.onrender.com
          mkdir -p dist
          cp build/app/outputs/flutter-apk/app-debug.apk "dist/app-debug-${{ github.ref_name }}.apk"

      - name: Create/Upload GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: dist/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
